In [1]:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '3'

In [2]:
# Numpy's PRNG (Psuedo Random Number Generation) is based on a global state.
# Jax needs parallelizable, vectorizable and reproducible PRNG.

In [3]:
import jax
import jax.numpy as jnp

In [5]:
jax.random.PRNGKey(0)

Array([0, 0], dtype=uint32)

In [7]:
k = jax.random.key(0)

In [12]:
k1 = jax.random.split(k, 1)

In [13]:
k1

Array((1,), dtype=key<fry>) overlaying:
[[ 928981903 3453687069]]

In [10]:
k2

Array((), dtype=key<fry>) overlaying:
[2718843009 1272950319]

In [14]:
# IMPORTANT: Feeding the same key produces the same random output. Recycling keys is very important.

In [16]:
jax.random.split(jax.random.key(0), 2)

Array((2,), dtype=key<fry>) overlaying:
[[4146024105  967050713]
 [2718843009 1272950319]]

In [17]:
jax.random.split(jax.random.key(0), 2)

Array((2,), dtype=key<fry>) overlaying:
[[4146024105  967050713]
 [2718843009 1272950319]]

In [18]:
# Jax does not guarentee sequential equivalence, as it runs parallelly in the backend.